# Generated by Django 4.2.25 on 2025-10-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamework',
            fields=[
                ('gamework_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Gamework ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Gamework',
                'verbose_name_plural': 'Gameworks',
                'ordering': ['-created_at'],
            },
        ),
    ]
