# Generated by Django 4.2.25 on 2025-10-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('gameworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamework',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameworks', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='gamework',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='gameworks', to='tags.tag', verbose_name='Tags'),
        ),
    ]
