export const defaultTags = [
  // 类型标签（1-16）
  { id: 1, name: '玄幻' },
  { id: 2, name: '奇幻' },
  { id: 3, name: '仙侠' },
  { id: 4, name: '武侠' },
  { id: 5, name: '科幻' },
  { id: 6, name: '都市' },
  { id: 7, name: '历史' },
  { id: 8, name: '军事' },
  { id: 9, name: '悬疑' },
  { id: 10, name: '灵异' },
  { id: 11, name: '惊悚' },
  { id: 12, name: '游戏' },
  { id: 13, name: '竞技' },
  { id: 14, name: '体育' },
  { id: 15, name: '言情' },
  { id: 16, name: '现实' },

  // 风格标签（17-49）
  { id: 17, name: '升级流' },
  { id: 18, name: '无敌流' },
  { id: 19, name: '重生' },
  { id: 20, name: '穿越' },
  { id: 21, name: '系统' },
  { id: 22, name: '无限流' },
  { id: 23, name: '种田' },
  { id: 24, name: '基建' },
  { id: 25, name: '末世' },
  { id: 26, name: '废土' },
  { id: 27, name: '爽文' },
  { id: 28, name: '轻松' },
  { id: 29, name: '搞笑' },
  { id: 30, name: '治愈' },
  { id: 31, name: '暗黑' },
  { id: 32, name: '虐心' },
  { id: 33, name: '烧脑' },
  { id: 34, name: '智斗' },
  { id: 35, name: '群像' },
  { id: 36, name: '日常' },
  { id: 37, name: '生活流' },
  { id: 38, name: '热血' },
  { id: 39, name: '争霸' },
  { id: 40, name: '权谋' },
  { id: 41, name: '扮猪吃虎' },
  { id: 42, name: '腹黑' },
  { id: 43, name: '忠犬' },
  { id: 44, name: '傲娇' },
  { id: 45, name: '病娇' },
  { id: 46, name: '萌宝' },
  { id: 47, name: '马甲' },
  { id: 48, name: '神豪' },
  { id: 49, name: '赘婿' },

  // 世界观标签（50-64）
  { id: 50, name: '现代' },
  { id: 51, name: '古代' },
  { id: 52, name: '异界' },
  { id: 53, name: '异世界' },
  { id: 54, name: '星际' },
  { id: 55, name: '未来' },
  { id: 56, name: '民国' },
  { id: 57, name: '原始社会' },
  { id: 58, name: '原始部落' },
  { id: 59, name: '洪荒' },
  { id: 60, name: '高武' },
  { id: 61, name: '西幻' },
  { id: 62, name: '克鲁苏' },
  { id: 63, name: '赛博朋克' },
  { id: 64, name: '蒸汽朋克' },

  // 题材标签（65-89）
  { id: 65, name: '男频' },
  { id: 66, name: '女频' },
  { id: 67, name: '甜宠' },
  { id: 68, name: '霸总' },
  { id: 69, name: '女强' },
  { id: 70, name: '女尊' },
  { id: 71, name: '宫斗' },
  { id: 72, name: '宅斗' },
  { id: 73, name: '职场' },
  { id: 74, name: '职场商战' },
  { id: 75, name: '校园' },
  { id: 76, name: '青春' },
  { id: 77, name: '耽美' },
  { id: 78, name: '百合' },
  { id: 79, name: '明星同人' },
  { id: 80, name: '二次元' },
  { id: 81, name: '轻小说' },
  { id: 82, name: '影视改编' },
  { id: 83, name: '出版小说' },
  { id: 84, name: '真人互动' },
  { id: 85, name: '多人视角' },
  { id: 86, name: '第一人称' },
  { id: 87, name: '第二人称' },
  { id: 88, name: '第三人称' },
  { id: 89, name: '单元剧' }
]
