"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import logging
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k$yb$ixo21c3ci)k)l)mp*#79)7u0_5%xbfr-r_hrv1@p5$$ud'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '',
    'localhost',
    'localhost:8000',
    '127.0.0.1',
    'http://localhost:5173', 
    'http://127.0.0.1:5173', 
    '0.0.0.0'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS支持
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist', 
    'drf_spectacular',
    'drf_yasg',
    'users',  # 用户
    'gameworks',  # 游戏作品
    'tags',  # 标签
    'interactions',  # 收藏/评分/评论
    'game',
    'stories',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL 数据库引擎
        'NAME': 'mydatabase',          # 数据库名
        'USER': 'test_user',               # 数据库用户名
        'PASSWORD': 'test_password',           # 数据库密码
        'HOST': 'localhost',                   # 数据库主机，默认本地 localhost
        'PORT': '3306',                        # MySQL 默认端口
        'OPTIONS': {                           # 可选配置
            'charset': 'utf8mb4',              # 字符集
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,  # 数据库锁等待超时时间(秒),增加到30秒
            'init_command': (
                "PRAGMA journal_mode=WAL;"  # 使用 WAL 模式提高并发性能
                "PRAGMA synchronous=NORMAL;"  # 平衡性能和安全性
                "PRAGMA busy_timeout=30000;"  # 30秒超时
                "PRAGMA temp_store=MEMORY;"  # 使用内存存储临时数据
                "PRAGMA cache_size=-64000;"  # 64MB 缓存
            ),
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 用于拼接绝对 URL（例如为 AI 生成的图片或 media 文件构造完整访问地址）
# 可通过环境变量 SITE_DOMAIN 覆盖（例如在生产中设置为 https://yourdomain.com）
SITE_DOMAIN = os.getenv('SITE_DOMAIN', 'http://localhost:8000')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 指定用户模型
AUTH_USER_MODEL = 'users.User'


# 完全关闭权限验证
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # 使用JWT认证
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # 只有认证用户才能执行操作
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

from datetime import timedelta

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Bearer {your token}"',
        }
    },
    'USE_SESSION_AUTH': True,
    'LOGIN_URL': 'rest_framework:login',
    'LOGOUT_URL': 'rest_framework:logout',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=800),   # 短期访问 token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # 长期刷新 token
}


# 邮箱发送验证码服务
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.163.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 465))
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)



CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # 替换为实际IP
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        #'require_debug_false': {
        #    '()': 'django.utils.log.RequireDebugFalse',
        #},
        'error_only': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: record.levelno == logging.ERROR,
        },
        'info_and_warning_only': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: record.levelno in (logging.INFO, logging.WARNING),
        },
    },
    'handlers': {
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django_errors.log'),
            'formatter': 'verbose',
            'filters': ['error_only'],
            'encoding': 'utf-8',
        },
        'info_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django_infos.log'),
            'formatter': 'simple',
            'filters': ['info_and_warning_only'],
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['error_file', 'info_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================
# CORS配置
# ============================================

# 方法1：允许所有 origins（开发环境）
CORS_ALLOW_ALL_ORIGINS = True

# 或者方法2：指定允许的 origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# 允许携带凭证（cookies, authorization headers 等）
CORS_ALLOW_CREDENTIALS = True

# 允许的 HTTP 方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许的 headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Authorization',
    'Content-Type',
    'Referrer',
    'User-Agent',
]

# 如果需要，也可以显式设置允许的 origins（与 CORS_ALLOWED_ORIGINS 相同）
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
AI_MODEL_FOR_TEXT = "DeepSeek-V3.2-Exp"
AI_API_KEY_FOR_TEXT = "sk-PAF8gzAL93s9xKlaybzSQw"
AI_BASE_URL_FOR_TEXT = "https://llmapi.paratera.com/v1/"

AI_MODEL_FOR_IMAGE = "doubao-seedream-4-0-250828"
AI_API_KEY_FOR_IMAGE = "d62d3ca8-3892-446f-9400-e2164e441bee"
AI_BASE_URL_FOR_IMAGE = "https://ark.cn-beijing.volces.com/api/v3"
