# Generated by Django 5.2.7 on 2025-10-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gameworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_chapters",
                    models.PositiveIntegerField(default=3, help_text="计划总章节数"),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, help_text="故事是否已完成生成"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gamework",
                    models.OneToOneField(
                        help_text="关联的游戏作品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story",
                        to="gameworks.gamework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoryChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter_index",
                    models.PositiveIntegerField(help_text="章节序号 (从1开始)"),
                ),
                ("content", models.JSONField(help_text="章节内容的JSON结构")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        help_text="关联的故事",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "ordering": ["story", "chapter_index"],
                "unique_together": {("story", "chapter_index")},
            },
        ),
    ]
